import java.util.Scanner;

class Exception_handling{
    public static void main(String[] args) {
        Scanner sc=new Scanner(System.in);
        int num1,num2,result;
        try {
            System.out.println("Enter the first number");
            num1 = Integer.parseInt(sc.next());
            System.out.println("Enter the second number");
            num2 = Integer.parseInt(sc.next());
            result = num1 / num2;
            System.out.println("divsion is: " + result);
            int []arr={1,2,3,4};
            System.out.println(arr[4]);
        }
        catch(NumberFormatException e){
            System.out.println("Number is invalid ");
        }
        catch(ArithmeticException e){
            System.out.println("Denominator is zero Arithmatic Exception Occure: ");
        }
        catch(ArrayIndexOutOfBoundsException e){
            System.out.println("Array index out of bound Exception Occure: ");
        }
    }
}
